### ISSUE TITLE
When will the code be updated?

### ISSUE THREAD

**Issue by Houwentai** [miccaiif/DGMIL#1]
Thanks for your nice work!
When will the code be updated?

**Comment by hust-linyi** [comment]
Looking forward to your update, cheers!

**Comment by miccaiif** [comment]
Hello! Main models are uploaded and the original MAE features and distance files are on updating...

**Comment by FoilHao** [comment]
utils module is imported in pos_score_calculator.py，but there isn't an util.py

**Comment by Raymvp** [comment]
> Hello! Main models are uploaded and the original MAE features and distance files are on updating...

请问现在上传好了吗？

**Comment by Raymvp** [comment]
> utils module is imported in pos_score_calculator.py，but there isn't an util.py
Have you solved this problem?

**Comment by miccaiif** [comment]
> utils module is imported in pos_score_calculator.py，but there isn't an util.py

Thank you for raising this question. Due to our oversight, we did not notice this issue. We have now added the utils file.

**Comment by miccaiif** [comment]
> > utils module is imported in pos_score_calculator.py，but there isn't an util.py
> > Have you solved this problem?

Thank you for raising this question. Due to our oversight, we did not notice this issue. We have now added the utils file.

**Comment by miccaiif** [comment]
> > Hello! Main models are uploaded and the original MAE features and distance files are on updating...
> 
> 请问现在上传好了吗？

您好，感谢关注！正如readme中提到的，patching的操作您可以参考DSMIL这篇文章的操作（也是我们参考的文章）。由于不同MIL试验的设置不同（例如patch size，scale等），所以需要根据您自己的试验设置进行patching。自监督特征提取您可以参考MAE的官方代码，也有很多已训练好的模型可以使用。完全上传这些所有的feats文件需要大量时间和空间，我们已开源主要和关键的代码模型，readme中的引导和上述引导可以支持复现本工作，再次感谢您的关注！
