### ISSUE TITLE
关于实验结果问题

### ISSUE THREAD

**Issue by AndrewTal** [miccaiif/DGMIL#6]
您好，我看到论文中DSMIL (CVPR’21) 的 Slide ACC 只有  0.7359，而 DSMIL 原始论文中Slide ACC 可以达到 0.8682，请问造成结果差异的原因是什么？感谢！

**Comment by HardworkingLittlequ** [comment]
你好，感谢你的关注！为了考虑计算效率和资源，我们在实验中使用了5倍（相对于DSMIL的20倍）的计算资源。我们使用的patch尺寸是512（相对于DSMIL的224），如果一个patch中包含25％或更多的癌症区域，则将其标记为阳性（在DSMIL中没有具体说明，详见其代码）。这些不同的设置可能会导致我们报告的指标与DSMIL报告的指标之间的差异。
