### ISSUE TITLE
How to classify testing slides?

### ISSUE THREAD

**Issue by qyn0729** [miccaiif/DGMIL#8]
Thank you for your great work!

The paper mentioned that "For bag-level classification, we only use the simple mean- pooling approach to aggregate the positive scores of all instances in a bag." How do you set the threshold value to distinguish between negative and positive bags in the testing set?

**Comment by miccaiif** [comment]
Hello! Thank you for your attention! The threshold was selected based on the validation set. In fact, our goal is to obtain a good instance classifier, and as for the bag-level classification, any other method can be used for aggregation based on the output of the instance classifier, including re-fitting the bag boundaries. In the text, to demonstrate the effectiveness of our instance classifier, we only used mean pooling to obtain the bag prediction.
